# Generated by Django 5.2.4 on 2026-07-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OPERATOR', 'Оператор'), ('VIEWER', 'Руководитель'), ('ADMIN', 'Администратор')], default='VIEWER', max_length=20, verbose_name='Роль'),
        ),
    ]
