# Generated by Django 5.2.4 on 2026-07-14 11:40

import django.db.models.deletion
import journal.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название услуги')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Медицинская услуга',
                'verbose_name_plural': 'Медицинские услуги',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fio', models.CharField(db_index=True, max_length=255, verbose_name='ФИО пациента')),
                ('patient_snils', models.CharField(max_length=14, validators=[journal.validators.validate_snils], verbose_name='СНИЛС')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('desired_date', models.DateField(db_index=True, validators=[journal.validators.validate_future_date], verbose_name='Желаемая дата приёма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Завершена'), ('CANCELLED', 'Отменена')], db_index=True, default='NEW', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='journal.medicalservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Завершена'), ('CANCELLED', 'Отменена')], max_length=20, verbose_name='Статус ИЗ')),
                ('to_status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Завершена'), ('CANCELLED', 'Отменена')], max_length=20, verbose_name='Статус В')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Момент изменения')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='journal.medicalrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'Истории статусов',
                'db_table': 'request_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
