# Generated by Django 5.2.4 on 2026-07-15 05:25

import journal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrequest',
            name='desired_date',
            field=models.DateField(validators=[journal.validators.validate_future_date], verbose_name='Желаемая дата приёма'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='patient_fio',
            field=models.CharField(max_length=255, verbose_name='ФИО пациента'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Завершена'), ('CANCELLED', 'Отменена')], default='NEW', max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
