# Generated by Django 5.2.4 on 2026-07-19 17:49

import journal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_medicalrequest_desired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrequest',
            name='patient_fio',
            field=models.CharField(max_length=255, validators=[journal.validators.validate_fio], verbose_name='ФИО пациента'),
        ),
        migrations.AlterField(
            model_name='medicalrequest',
            name='patient_phone',
            field=models.CharField(max_length=20, validators=[journal.validators.validate_phone], verbose_name='Телефон'),
        ),
    ]
